version: "3.7"
services:
  mqtt-broker:
    image: "am2h/mqtt:2.0"
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
     - mqtt_data:/mosquitto/data
     - mqtt_log:/mosquitto/log
     - mqtt_user:/mosquitto/pw
    networks:
      mqtt:
        aliases:
          - mqtt-broker
  mqtt-client:
    image: "am2h/mqtt-webclient:latest"
    restart: unless-stopped
    ports:
      - "9002:80"
    networks:
      mqtt:
        aliases:
          - mqtt-client

volumes:
  mqtt_data:
  mqtt_log:
  mqtt_user:

networks:
  mqtt:
