version: "3.7"
services:
  mqtt-broker:
    image: "am2h/mqtt:2.1"
    restart: unless-stopped
    ports:
      - "1883:1883"
      #- "1884:1884"
      #- "9001:9001"
    volumes:
     - mqtt_data:/mosquitto/data
     - mqtt_log:/mosquitto/log
     - mqtt_user:/mosquitto/user
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.mqtt.rule=Host(`mqtt.${HOST}`)"
      - "traefik.http.routers.mqtt.entrypoints=websecure"
      - "traefik.http.routers.mqtt.tls.certresolver=myresolver"

      - "traefik.tcp.routers.mqtt.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.mqtt.tls.certresolver=myresolver"
      - "traefik.tcp.services.mqtt.loadbalancer.server.port=1884"
      
      - "traefik.tcp.routers.mqtt.entrypoints=mqtt"

      - "traefik.http.services.mqtt.loadbalancer.server.port=9001"

      
    networks:
      net:

  mqtt-client:
    image: "am2h/mqtt-webclient:latest"
    restart: unless-stopped
    ports:
      - "9002:80"
    networks:
      net:

volumes:
  mqtt_data:
  mqtt_log:
  mqtt_user:

networks:
  net:
   external:
     name: traefik_net
