version: "3.7"
services:
  mqtt-broker:
    image: "am2h/mqtt:2.0"
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "1884:1884"
      - "9001:9001"
    volumes:
     - mqtt_data:/mosquitto/data
     - mqtt_log:/mosquitto/log
     - mqtt_user:/mosquitto/user
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_net"
      - "traefik.tcp.services.mqtt.loadbalancer.server.port=1884"
      - "traefik.http.routers.tcpr_mqtt.tls.certresolver=myresolver"
      - "traefik.tcp.routers.tcpr_mqtt.entrypoints=mqtt"
      - "traefik.tcp.routers.tcpr_mqtt.rule=HostSNI(`home.${HOST}`)"
      - "traefik.tcp.routers.tcpr_mqtt.service=mqtt"
    networks:
      net:
      mqtt:
        aliases:
          - mqtt-broker
  mqtt-client:
    image: "am2h/mqtt-webclient:latest"
    restart: unless-stopped
    ports:
      - "9002:80"
    networks:
      mqtt:
        aliases:
          - mqtt-client

volumes:
  mqtt_data:
  mqtt_log:
  mqtt_user:

networks:
  mqtt:
  net:
   external:
     name: traefik_net
