version: "3.7"
services:
  mqtt-broker:
    image: "am2h/mqtt:2.0"
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
     - mqtt_data:/mosquitto/data
     - mqtt_log:/mosquitto/log
     - mqtt_user:/mosquitto/user
    labels:
     - "traefik.enable=true"
     # - "traefik.docker.network=mqtt"
     - "traefik.tcp.services.mqtt.loadbalancer.server.port=1884"
     # - "traefik.tcp.services.mqtt_websocket.loadbalancer.server.port=9001"
     - "traefik.tcp.routers.tcpr_mqtt.entrypoints=mqtt"
     - "traefik.tcp.routers.tcpr_mqtt.rule=HostSNI(`*`)"
     - "traefik.tcp.routers.tcpr_mqtt.service=mqtt"
     # - "traefik.tcp.routers.tcpr_mqtt_websocket.entrypoints=websocket"
     # - "traefik.tcp.routers.tcpr_mqtt_websocket.rule=HostSNI(`*`)"
     # - "traefik.tcp.routers.tcpr_mqtt_websocket.service=mqtt_websocket"
    networks:
      net:
      mqtt:
        aliases:
          - mqtt-broker
  mqtt-client:
    image: "am2h/mqtt-webclient:latest"
    restart: unless-stopped
    ports:
      - "9002:80"
    networks:
      mqtt:
        aliases:
          - mqtt-client

volumes:
  mqtt_data:
  mqtt_log:
  mqtt_user:

networks:
  mqtt:
  net:
   external:
     name: traefik_net
