version: "3.7"
services:
  mqtt:
    image: "eclipse-mosquitto:latest"
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
     - mqtt_data:/mosquitto/data
     - mqtt_log:/mosquitto/log
     - mqtt_conf:/mosquitto/config
volumes:
  mqtt_data:
  mqtt_log:
  mqtt_conf:
